"""Inital migration

Revision ID: f573b82b028d
Revises:
Create Date: 2025-07-09 19:39:13.383818

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f573b82b028d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
