name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-groups

    - name: Run ruff check
      run: uv run ruff check .

    - name: Run ruff format
      run: uv run ruff format .

    - name: Run mypy
      run: uv run mypy .

    - name: Run tests with coverage
      run: uv run pytest --cov=app --cov-report=xml --cov-report=term-missing
